[package]
name = "dfiles"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "lib/dfilesfiles",
  "app/chrome",
  "app/firefox",
  "app/signal",
  "app/skype",
  "app/steam",
]

[lib]
name = "dfiles"
path = "src/dfiles/mod.rs"

[dependencies]
shiplift = "0.5"
dockworker = "0.0.14"
tokio = "0.1"
serde = "1.0"
hyper = "0.12.35"
serde_json = "1.0"
tempfile = "3.1.0"
tar = "0.4.26"

clap = "2.33"
