[package]
name = "firefox"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dfiles = { path = "../../" }
tempfile = "3.1.0"
tar = "0.4.26"
